"""connecting the category table with the recipe table properly

Revision ID: ca0b4e0db6a2
Revises: 41b3e2cffcae
Create Date: 2023-03-11 14:00:51.324394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca0b4e0db6a2'
down_revision = '41b3e2cffcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_categories')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recipe_id')

    op.create_table('recipe_categories',
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='recipe_categories_ibfk_1'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='recipe_categories_ibfk_2'),
    sa.PrimaryKeyConstraint('recipe_id', 'category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
